when:
  branch: main
  event: push

steps:
  lint-dockerfile.io:
    image: hadolint/hadolint:v2.12.1-beta-alpine
    depends_on: []
    commands:
      - hadolint --ignore DL3003 --ignore DL3018 Dockerfile.io

  lint-dockerfile.app:
    image: hadolint/hadolint:v2.12.1-beta-alpine
    depends_on: []
    commands:
      - hadolint --ignore DL3003 --ignore DL3018 Dockerfile.app

  lint-dockerfile.worker:
    image: hadolint/hadolint:v2.12.1-beta-alpine
    depends_on: []
    commands:
      - hadolint --ignore DL3003 --ignore DL3018 Dockerfile.worker

  docker-build:
    image: woodpeckerci/plugin-docker-buildx:5.2.2
    settings:
      dry_run: true
      pull_image: false
      dockerfile: Dockerfile.io
      buildkit_driveropt:
        - "image=moby/buildkit:master"
