when:
  branch: main
  event: push

steps:
  dockle:
    image: euryecetelecom/woodpeckerci-dockle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    settings:
      dockerfile: Dockerfile.app
      dockle-ignores: CIS-DI-0006

  docker-build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dry_run: true
      dockerfile: Dockerfile.io
